### PR TITLE
Add past sponsors

### PR DESCRIPTION
**Pull request by lee-ma**
Screen Shot 2019-03-31 at 10 12 15 AM
Screen Shot 2019-03-31 at 10 12 40 AM
Screen Shot 2019-03-31 at 10 15 41 AM

### CODE REVIEW

**Review by ikelee — COMMENTED** [review]
Just gonna get Winnie to confirm all the past sponsors.

**Comment by winnieren** [comment]
Missing: Rangle.IO (they were gold last year so pretty important) and consensys (silver)

list of past sponsors here: http://enghack.uwaterloo.ca/

**Comment by lee-ma** [comment]
Screen Shot 2019-03-31 at 8 54 39 PM

**Comment by ikelee** [comment]
👍

**Review by ikelee — APPROVED** [review]

**Pull request merged**
